### ISSUE TITLE
Package client service file and config in velociraptor rpm

### ISSUE THREAD

**Issue by dmach** [SUSE/linux-security-sensor#5]
While `velociraptor-client` package contains only client, `velociraptor` package contains both server and client functionality.
Unfortunately, the following client files are not part of the `velociraptor` package:
```
/etc/velociraptor/client.config
/usr/lib/systemd/system/velociraptor-client.service
```

**Comment by jeffmahoney** [comment]
Yep, that makes sense.  I've added the config and service file to the velociraptor package: https://build.opensuse.org/request/show/952778
